import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useState } from "react";
import { Menu, X } from "lucide-react";
import LoginModal from "./ui/LoginModal"; // Asegúrate de tener este componente
const Navbar = () => {
    const [isOpen, setIsOpen] = useState(false);
    const [isLoginOpen, setIsLoginOpen] = useState(false);
    return (_jsxs(_Fragment, { children: [_jsx("header", { className: "fixed top-0 left-0 w-full z-50 bg-white shadow-md px-6 py-4", children: _jsxs("div", { className: "max-w-7xl mx-auto flex items-center justify-between", children: [_jsx("div", { className: "flex-1", children: _jsx("h1", { className: "text-2xl font-bold text-gray-900", children: "Corredur\u00EDa Integral" }) }), _jsxs("nav", { className: "hidden md:flex flex-1 justify-center gap-6 text-gray-700", children: [_jsx("a", { href: "#services", className: "hover:text-blue-600", children: "Servicios" }), _jsx("a", { href: "#about", className: "hover:text-blue-600", children: "Sobre Nosotros" }), _jsx("a", { href: "#contact", className: "hover:text-blue-600", children: "Contacto" })] }), _jsxs("div", { className: "flex-1 flex justify-end items-center", children: [_jsx("button", { onClick: () => setIsLoginOpen(true), className: "hidden md:inline-block bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 transition", children: "Acceso / Registro" }), _jsx("button", { onClick: () => setIsOpen(true), className: "md:hidden text-gray-700", "aria-label": "Abrir men\u00FA", children: _jsx(Menu, { size: 28 }) })] })] }) }), _jsx(LoginModal, { isOpen: isLoginOpen, onClose: () => setIsLoginOpen(false) }), _jsxs("div", { className: `fixed top-0 right-0 h-full w-64 bg-white shadow-lg z-50 transform transition-transform duration-300 md:hidden ${isOpen ? "translate-x-0" : "translate-x-full"}`, children: [_jsxs("div", { className: "flex items-center justify-between p-4 border-b", children: [_jsx("span", { className: "text-lg font-semibold", children: "Men\u00FA" }), _jsx("button", { onClick: () => setIsOpen(false), "aria-label": "Cerrar men\u00FA", children: _jsx(X, { size: 24 }) })] }), _jsxs("nav", { className: "flex flex-col p-4 space-y-4 text-gray-700", children: [_jsx("a", { href: "#services", onClick: () => setIsOpen(false), className: "hover:text-blue-600", children: "Servicios" }), _jsx("a", { href: "#about", onClick: () => setIsOpen(false), className: "hover:text-blue-600", children: "Sobre Nosotros" }), _jsx("a", { href: "#contact", onClick: () => setIsOpen(false), className: "hover:text-blue-600", children: "Contacto" }), _jsx("button", { onClick: () => {
                                    setIsLoginOpen(true);
                                    setIsOpen(false);
                                }, className: "hover:text-blue-600 text-left", children: "Acceso / Registro" })] })] }), isOpen && (_jsx("div", { className: "fixed inset-0 bg-black bg-opacity-40 z-40 md:hidden", onClick: () => setIsOpen(false) }))] }));
};
export default Navbar;
